#server
server:
  port: 8080

spring:
  #datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin
  #配置静态资源放行
  mvc:
    static-path-pattern: /static/**
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml






